<a href="https://colab.research.google.com/github/shriya-shubhi/teenhackshtx_submission/blob/master/class_match_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Title: Leveraging **Machine learning** to optimize virtual **class matching** for high schoolers for best learning **experience**





Problem: During the corona virus time, many high-schoolers have been following different schedule of study. Some have been an early risers while others night owls. This pattern results in each high schoolers having a different times when he / she is alert. However, regardless of alertness, all of them have to attends the classes time.

**Solution**: This program will learn from the high-schoolers activity pattern throughout the day. Based on the students alertness time zone, it will connect with the school, so that the teachers can use the information.



*   Wake-up time
*   Sleep time
*   Eating time(s)
*   Snacking time(s)
*   Home work time(s)
*   Exercise time(s)
*   Social time(s)
*   Social Media time (s)
*   Screen time(s)








# HOW did we do it?
### Define the actitivies we capture

In [0]:
all_activtities = [
            'wakeup_time',
            'first_snack_time',
            'second_snack_time',
            'home_work_time',
            'exercise_1_time',
            'exercise_2_time',
            'reading_time',
            'social_media_time',
            'freinds_and_family_time',
            'health_condition',
            ]

### Activities we have tested so far.

In [0]:
tested_activities = ['wakeup_time', 'sleep_time']

### Import Libraries 

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

### Generate Synthetic Data for each activity

In [60]:
wake_up_times = np.random.randint(low=4, high=11, size=10000)
sleep_times = np.random.randint(low=18, high=24, size=10000)
snack_times = np.random.randint(low=10, high=16, size=10000)
ex_times = np.random.randint(low=15, high=20, size=10000)
print("sample wake up data: ", wake_up_times[:5])
print("sample sleep  data: ", sleep_times[:5])

sample wake up data:  [ 7  6 10  7 10]
sample sleep  data:  [18 21 19 22 21]


### Label the type of student based on Synthetic data

In [72]:
#We are checking if a student wakes up before 8 and sleeps before 9pm, then student is a morning person
morning_person = [ 1 if x < 8 and y < 21 else 0 for x, y in zip(wake_up_times,sleep_times)]
morning_person[:5]

[1, 0, 0, 0, 0]

### Prepare the activity data for Machine learning Model

In [43]:
l1 = [wake_up_times, sleep_times, morning_person]
activities_dataframe = pd.DataFrame( columns=['Wakeup_time', 'sleep_time', 'morning_person'])

activities_dataframe['Wakeup_time'] = wake_up_times
activities_dataframe['sleep_time'] = sleep_times
activities_dataframe['morning_person'] = morning_person
print("\t ***First FiveMorning Persos******\n")
print( activities_dataframe[activities_dataframe['morning_person'] == 1][:5])

	 ***First FiveMorning Persos******

    Wakeup_time  sleep_time  morning_person
1             6          18               1
2             4          20               1
8             5          18               1
12            5          19               1
13            6          19               1


In [44]:
print("\t ****First Five Evening Persos***\n")
print( activities_dataframe[activities_dataframe['morning_person'] == 0][:5])

	 ****First Five Evening Persos***

   Wakeup_time  sleep_time  morning_person
0            8          20               0
3            8          22               0
4            9          20               0
5            9          19               0
6            4          21               0


### Create a MATRIX of Data for Machine Learning Model

In [45]:
X = activities_dataframe.iloc[:,[0,1]].values
X[:5]

array([[ 8, 20],
       [ 6, 18],
       [ 4, 20],
       [ 8, 22],
       [ 9, 20]])

In [46]:
y = activities_dataframe.iloc[:,2].values
y[:5]

array([0, 1, 1, 0, 0])

### Data splitting for Training and Testing the model

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)
print("triaining data", X_train[:5])

triaining data [[ 5 20]
 [ 5 18]
 [ 5 22]
 [ 4 19]
 [ 7 22]]


### Scaling of Data

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
X_test[:5]

array([[ 0.48974614,  1.45933685],
       [-1.50217146,  0.28422129],
       [ 1.48570494,  0.28422129],
       [ 0.48974614,  0.28422129],
       [ 0.48974614,  0.28422129]])

# Create a Machine Learning Model

In [50]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state =0)
print("Logistic Regression Model", model)

Logistic Regression Model LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


# Train the Machine Learning Model

In [56]:
print("training data :>>", X_train[5:25])
print("training label:>>", y_train[5:25])

training data :>> [[ 5 19]
 [ 4 18]
 [ 9 21]
 [ 5 23]
 [ 7 22]
 [10 22]
 [10 19]
 [ 7 23]
 [ 6 18]
 [ 5 22]
 [ 5 18]
 [ 5 22]
 [ 6 19]
 [ 9 19]
 [ 4 23]
 [10 18]
 [10 18]
 [ 9 18]
 [ 6 18]
 [ 8 18]]
training label:>> [1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0]


In [62]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Use the Model to Classify the category of student

In [66]:
print("test data", X_test[:5])
print("test lable", y_test[:5])
#0,1,0,0,0

test data [[ 9 21]
 [ 7 18]
 [ 5 23]
 [ 6 21]
 [ 8 23]]
test lable [0 1 0 0 0]


In [65]:
y_pred = model.predict(X_test)
y_pred[:5]

array([0, 1, 0, 0, 0])

# Prediction 


In [71]:
accuracy  = model.score(X_test, y_test)
print("Accuracy of model >>>", accuracy * 100, "%<<<")

Accuracy of model >>> 90.7 %<<<
